---
# tasks file for netboot_server
  - name: installing packages
    yum:
      name: "{{ item }}"
      state: present
    loop: "{{ packages }}"
    when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution_major_version'] == '7'

  - name: configuring tftp
    lineinfile:
      path: /etc/xinetd.d/tftp
      regexp: "disable"
      line: "        disable                 = no"

  - name: start and enable xinetd
    service: 
     name: xinetd
     state: started
     enabled: yes

  - name: start and enable httpd
    service: 
     name: httpd
     state: started
     enabled: yes

  - name: copy syslinux files to tftp
    copy:
      src: "/usr/share/syslinux/{{ item }}"
      dest: "/var/lib/tftpboot/{{ item }}"
      remote_src: yes
    loop: "{{ remote_files }}"  

  - name: downloading CentOS 7 iso image
    get_url: 
      url: "{{ centos7_iso_url }}"
      dest: /tmp/Centos7
      checksum: "{{ centos7_iso_checksum }}"
  
  - name: downloading CentOS 8 iso image
    get_url:
      url: "{{ centos8_iso_url }}"
      dest: /tmp/Centos8
      checksum: "{{ centos8_iso_checksum }}"

  - name: create a public ftp dir for CentOS 7
    file:
      path: /var/ftp/pub/centos7
      state: directory
      recurse: yes
      mode: '0755'
  
  - name: create a public ftp dir for CentOS 8
    file:
      path: /var/ftp/pub/centos8
      state: directory
      recurse: yes
      mode: '0755'

  - name: create a temp dir for centos7 image
    file:
      path: /tmp/mounted/Centos7
      state: directory
  
  - name: create a temp dir for centos8 image
    file:
      path: /tmp/mounted/Centos8
      state: directory

  - name: mount CentOS 7 iso
    command: mount -o loop /tmp/Centos7 /tmp/mounted/Centos7
    ignore_errors: true
  
  - name: mount CentOS 8 iso
    command: mount -o loop /tmp/Centos8 /tmp/mounted/Centos8
    ignore_errors: true

  - name: sync mounted CentOS 7 iso to ftp dir
    synchronize:
     src: /tmp/mounted/Centos7/
     dest: /var/ftp/pub/centos7/
    delegate_to: "{{ inventory_hostname }}"

  - name: sync mounted CentOS 8 iso to ftp dir
    synchronize:
     src: /tmp/mounted/Centos8/
     dest: /var/ftp/pub/centos8/
    delegate_to: "{{ inventory_hostname }}"

  - name: create tftp netboot dir for centos 7
    file:
      path: /var/lib/tftpboot/networkboot/centos7
      state: directory
  
  - name: create tftp netboot dir for centos 8
    file:
      path: /var/lib/tftpboot/networkboot/centos8
      state: directory
  
  - name: copy CentOS 7 kernel and initrd to tftp dir
    copy:
      src: "/var/ftp/pub/centos7/images/pxeboot/{{ item }}"
      dest: "/var/lib/tftpboot/networkboot/centos7/{{ item }}"
      remote_src: yes
    loop:
    - vmlinuz
    - initrd.img

  - name: copy CentOS 8 kernel and initrd to tftp dir
    copy:
      src: "/var/ftp/pub/centos8/images/pxeboot/{{ item }}"
      dest: "/var/lib/tftpboot/networkboot/centos8/{{ item }}"
      remote_src: yes
    loop:
    - vmlinuz
    - initrd.img
    
  - name: create pxeboot config dir
    file:
     path: /var/lib/tftpboot/pxelinux.cfg
     state: directory

  - name: create kickstart web dir
    file:
     path: /var/www/html/inst
     state: directory

  - name: copy default pxe boot config file
    template:
      src: templates/default.j2
      dest: /var/lib/tftpboot/pxelinux.cfg/default

  - name: copy kickstart file CentOS 7
    template:
      src: templates/kickstart7.cfg.j2
      dest: /var/www/html/inst/ks7.cfg

  - name: copy kickstart file CentOS 8
    template:
      src: templates/kickstart8.cfg.j2
      dest: /var/www/html/inst/ks8.cfg

  - name: start and enable vsftpd
    service: 
     name: vsftpd
     state: started
     enabled: yes

  - name: configure firewall services
    firewalld:
      service: "{{ item }}"
      permanent: yes
      state: enabled
      immediate: true
    loop:
    - http
    - tftp 
    - ftp
